// <auto-generated />
using DayzMapsLoader.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DayzMapsLoader.Infrastructure.Migrations
{
    [DbContext(typeof(DayzMapLoaderContext))]
    partial class DayzMapLoaderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DayzMapsLoader.Infrastructure.Entities.DayzMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DayzMaps");
                });

            modelBuilder.Entity("DayzMapsLoader.Infrastructure.Entities.MapProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MapProviders");
                });

            modelBuilder.Entity("DayzMapsLoader.Infrastructure.Entities.ProvidersMapAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayzMapId")
                        .HasColumnType("int");

                    b.Property<int>("MapExtension")
                        .HasColumnType("int");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MapProviderId")
                        .HasColumnType("int");

                    b.Property<int>("MapType")
                        .HasColumnType("int");

                    b.Property<string>("MapVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxMapLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DayzMapId");

                    b.HasIndex("MapProviderId");

                    b.ToTable("ProvidersMapAssets");
                });

            modelBuilder.Entity("DayzMapsLoader.Infrastructure.Entities.ProvidersMapAsset", b =>
                {
                    b.HasOne("DayzMapsLoader.Infrastructure.Entities.DayzMap", "DayzMap")
                        .WithMany()
                        .HasForeignKey("DayzMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DayzMapsLoader.Infrastructure.Entities.MapProvider", "MapProvider")
                        .WithMany()
                        .HasForeignKey("MapProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayzMap");

                    b.Navigation("MapProvider");
                });
#pragma warning restore 612, 618
        }
    }
}
